services:
  frontend:
    image: blbu-vr-app-ui
    build:
      context: ../blbu_vr_app_ui
      dockerfile: ../docker/VR-APP-UI.Dockerfile
    restart: always
    ports:
      - '3000:3000'

  api:
    image: blbu-vr-app-service
    build:
      context: ../BLBU_VR_APP_SERVICE
      dockerfile: ../docker/VR-APP-SERVICE.Dockerfile
    restart: always
    depends_on:
      - db
    ports:
      - '${SERVER_PORT:-8080}:8080'
    env_file:
      - ../.env
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-prod}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL:-jdbc:mysql://db:3306/blbu_vr_app}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME:-root}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD:-password}
      FRONTEND_URL: ${FRONTEND_URL:-https://blbu-vr-app.duckdns.org}

  db:
    image: mysql:8.4.2
    command: --mysql-native-password=ON
    restart: always
    ports:
      - '3307:3306'
    env_file:
      - ../.env
    environment:
      MYSQL_ROOT_PASSWORD: ${SPRING_DATASOURCE_PASSWORD:-password}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-blbu_vr_app}
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
